### ISSUE TITLE
Error installing protobix

### ISSUE THREAD

**Issue by jeunito** [jbfavre/python-protobix#10]
Upon doing ```pip install protobix``` I get the following error: 

```bash
(logster)$ pip install functools
Downloading/unpacking functools
  Downloading functools-0.5.tar.gz
  Running setup.py (path:/home/jeune/.virtualenvs/logster/build/functools/setup.py) egg_info for package functools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/home/jeune/.virtualenvs/logster/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/home/jeune/.virtualenvs/logster/local/lib/python2.7/site-packages/setuptools/extension.py", line 3, in <module>
        import functools
      File "functools.py", line 72, in <module>
        globals()['c_%s' % x] = globals()[x] = getattr(_functools, x)
    AttributeError: 'module' object has no attribute 'compose'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "/home/jeune/.virtualenvs/logster/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>

    from setuptools.extension import Extension

  File "/home/jeune/.virtualenvs/logster/local/lib/python2.7/site-packages/setuptools/extension.py", line 3, in <module>

    import functools

  File "functools.py", line 72, in <module>

    globals()['c_%s' % x] = globals()[x] = getattr(_functools, x)

AttributeError: 'module' object has no attribute 'compose'
```

Downloading from github and doing ```python setup.py install``` works. Please update the documentation. Installing via pip seems to be broken.

**Comment by jbfavre** [comment]
Hello @jeunito 
Thanks for reporting this issue.

Actually, this is a known dependencies issue with 0.0.9

It's to be fixed in 0.1.1 which is currently in release candidate https://pypi.python.org/pypi/protobix/0.1.1rc2
Please test this version and report any issue

Regards
